const gameData = [
  {Choice: "Beginning", Text: "Test Text", Actions: ["array index 1", "array index 2"]},
  {Choice: "", Text: "", Actions: ""},
  {Choice: "", Text: "", Actions: ""},
  {Choice: "", Text: "", Actions: ""},
  {Choice: "", Text: "", Actions: ""},
  {Choice: "", Text: "", Actions: ""},
  {Choice: "", Text: "", Actions: ""},
  {Choice: "", Text: "", Actions: ""},
  {Choice: "", Text: "", Actions: ""},
  {Choice: "", Text: "", Actions: ""},
  {Choice: "", Text: "", Actions: ""},
  {Choice: "", Text: "", Actions: ""},
  {Choice: "", Text: "", Actions: ""},
  {Choice: "", Text: "", Actions: ""},
  {Choice: "", Text: "", Actions: ""},
]